services:
  payment-service:
    environment:
    - PORT=50058
    build:
      context: services/payment/
      dockerfile: Dockerfile
    ports:
      - "50058:50058"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - postgres_certs:/etc/ssl/postgres
      - ./:/app
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'payment-service' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  sso-service:
    environment:
    - PORT=50051
    build:
      context: services/sso/
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - postgres_certs:/etc/ssl/postgres
      - ./:/app
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'sso' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  billing-service:
    environment:
    - PORT=50052
    build:
      context: services/billing/
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      payment-service:
        condition: service_healthy
      sso-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - postgres_certs:/etc/ssl/postgres
      - ./:/app
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'billing' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  notification-service:
    build:
      context: services/notification/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      payment-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'notification-service' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_certs:/var/lib/postgresql/certs
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./scripts/postgres/init-ssl.sh:/var/lib/postgresql/certs/init-ssl.sh

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      bash -c "
        if [ ! -f /var/lib/postgresql/certs/server.crt ]; then
          bash /var/lib/postgresql/certs/init-ssl.sh
        fi
        exec docker-entrypoint.sh -c config_file=/etc/postgresql/postgresql.conf
      "
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1-management
    ports:
      - "5672:5672"  
      - "15672:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_certs:
  redis_data:
  rabbitmq_data: