services:
  transaction-service:
    environment:
    - PORT=50058
    build:
      context: services/transaction/
      dockerfile: Dockerfile
    ports:
      - "50058:50058"
    depends_on:
      postgres-transaction:
        condition: service_healthy
      redis-transaction:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    volumes:
      - ./:/app
    networks:
      - app_network
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'transaction-service' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  postgres-transaction:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-transaction:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  account-service:
    environment:
    - PORT=50052
    build:
      context: services/account/
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      postgres-account:
        condition: service_healthy
      redis-account:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    volumes:
      - ./:/app
    networks:
      - app_network
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'account-service' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  postgres-account:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/data 
    networks:
      - app_network   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-account:
    image: redis:8
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway-service:
    build:
      context: services/api-gateway/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      redis-api-gateway:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    volumes:
      - ./:/app
    networks:
      - app_network
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'api-gateway' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15      
  
  redis-api-gateway:
    image: redis:8
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  external-payment-service:
    environment:
    - PORT=8081
    build:
      context: services/external-payment/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    volumes:
      - ./:/app
    networks:
      - app_network
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'billing' || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 15

  kafka:
    extends:
      file: services/kafka/docker-compose.kafka.yml
      service: kafka
    networks:
      - app_network
      - kafka_network

  kafka-ui:
    extends:
      file: services/kafka/docker-compose.kafka.yml
      service: kafka-ui
    networks:
      - app_network
      - kafka_network

  kafka-init:
    extends:
      file: services/kafka/docker-compose.kafka.yml
      service: kafka-init
    networks:
      - app_network
      - kafka_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./services/postgres/servers.json:/pgadmin4/servers.json
    networks:
      - app_network
    depends_on:
      postgres-transaction:
        condition: service_healthy
      postgres-account:
        condition: service_healthy

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - app_network
    depends_on:
      redis-transaction:
        condition: service_healthy
      redis-account:
        condition: service_healthy
      redis-api-gateway:
        condition: service_healthy

networks:
  app_network:
    driver: bridge
    name: app_network
  kafka_network:

volumes:
  redis_data:
  postgres_data:
  kafka_data:
  pgadmin_data:
  redisinsight_data: