// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/external-payment": {
            "post": {
                "description": "Инициирует внешний платёж и отправляет его в Transaction Service через Kafka",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "external-payment"
                ],
                "summary": "Создать внешний платёж",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код счета отправителя",
                        "name": "sender_account_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Код счета получателя",
                        "name": "recipient_account_code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма платежа",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "RUB",
                            "USD",
                            "EUR"
                        ],
                        "type": "string",
                        "default": "RUB",
                        "description": "Валюта платежа",
                        "name": "currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание платежа",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Платёж успешно создан",
                        "schema": {
                            "$ref": "#/definitions/models.CreateExternalPaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateExternalPaymentResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "External payment initiated"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "External Payment Service API",
	Description:      "API эмулирует получение и обработку внешних платежей ISO8583",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
