server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri; 
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/ca.crt;
    ssl_certificate_key /etc/nginx/certs/ca.key;
    ssl_password_file /etc/nginx/certs/passphrase.txt;

    # Корень статики
    root /usr/share/nginx/web;

    # Статика (CSS, JS)
    location /static/ {
        alias /usr/share/nginx/web/static/;
        expires 30d;
        access_log off;
    }

    # Favicon
    location /favicon.ico {
        alias /usr/share/nginx/web/favicon.ico;
        expires max;
        access_log off;
    }

    # Перенаправление корня на /auth
    location = / {
        return 302 /auth;
    }

    # Основной location / 
    location / {
        try_files $uri.html $uri $uri/ @proxy_to_app;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Проксирование, если статика не найдена
    location @proxy_to_app {
        proxy_pass http://client-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}