version: '3'

vars:
  ROOT_DIR: "{{.TASKFILE_DIR}}/.."
  DAYS: "365"
  BITS: "4096"
  JWT_BITS: "2048"
  SERVICES: ["transaction", "sso", "billing", "client"]
  CA_PASS: "secret"

tasks:
  clean:
    desc: "Remove all generated certificates"
    cmds:
      - rm -rf "{{.ROOT_DIR}}/security/"*.{key,crt,csr,srl,pem, pfx}
      - rm -rf "{{.ROOT_DIR}}/services/transaction/security/"*.{key,crt,csr,srl,pem}
      - rm -rf "{{.ROOT_DIR}}/services/sso/security/"*.{key,crt,csr,srl,pem}
      - rm -rf "{{.ROOT_DIR}}/services/billing/security/"*.{key,crt,csr,srl,pem}
      - rm -rf "{{.ROOT_DIR}}/services/client/security/"*.{key,crt,csr,srl,pem}
      - echo "All certificates removed"

  generate-ca:
    desc: "Generate root CA certificate"
    cmds:
      - |
        mkdir -p "{{.ROOT_DIR}}/security"
      - |
        openssl genrsa -aes256 -passout pass:{{.CA_PASS}} -out "{{.ROOT_DIR}}/security/ca.key" {{.BITS}}
      - |
        openssl req -new -x509 -days {{$.DAYS}} -key "{{.ROOT_DIR}}/security/ca.key" -passin pass:{{.CA_PASS}} \
          -out "{{.ROOT_DIR}}/security/ca.crt" \
          -subj "/C=RU/ST=Moscow/L=Moscow/O=FinanceSystem/OU=Development/CN=FinanceSystem CA"
    generates:
      - "{{.ROOT_DIR}}/security/ca.key"
      - "{{.ROOT_DIR}}/security/ca.crt"

  copy-ca-to-services:
    desc: "Copy root CA certificate to all services"
    params:
      - name: SERVICE
        type: string
    cmds:
      - |
          {{range $service := .SERVICES}}
          mkdir -p "{{$.ROOT_DIR}}/services/{{$service}}/security" &&
          cp "{{$.ROOT_DIR}}/security/ca.crt" "{{$.ROOT_DIR}}/services/{{$service}}/security/ca.crt" &&
          {{end}}
          echo "CA certificate copied to all services"
    generates:
      - "{{range $service := .SERVICES}}{{$.ROOT_DIR}}/services/{{$service}}/security/ca.crt {{end}}"

  generate-service-certs:
    desc: "Generate certificate for all service"
    cmds:
      - task: generate-cert
        vars:
          SERVICE: "transaction"
      - task: generate-cert
        vars:
          SERVICE: "sso"
      - task: generate-cert
        vars:
          SERVICE: "billing"
      - task: generate-cert
        vars:
          SERVICE: "client"
    generates:
      - "{{.ROOT_DIR}}/services/transaction/security/transaction.key"
      - "{{.ROOT_DIR}}/services/transaction/security/transaction.crt"
      - "{{.ROOT_DIR}}/services/sso/security/sso.key"
      - "{{.ROOT_DIR}}/services/sso/security/sso.crt"
      - "{{.ROOT_DIR}}/services/billing/security/billing.key"
      - "{{.ROOT_DIR}}/services/billing/security/billing.crt"
      - "{{.ROOT_DIR}}/services/client/security/client.key"
      - "{{.ROOT_DIR}}/services/client/security/client.crt"

  generate-cert:
    desc: "Generate certificate"
    params:
      - name: SERVICE
        type: string
        desc: "Имя сервиса"
    cmds:
      - |
        mkdir -p "{{.ROOT_DIR}}/services/{{.SERVICE}}/security"
      - |
        openssl genrsa -out "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/{{.SERVICE}}.key" 2048
      - |
        openssl req -new -key "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/{{.SERVICE}}.key" \
          -out "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/{{.SERVICE}}.csr" \
          -config "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/cert.conf"
      - |
        openssl x509 -req -days {{$.DAYS}} -in "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/{{.SERVICE}}.csr" \
          -CA "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/ca.crt" \
          -CAkey "{{.ROOT_DIR}}/security/ca.key" -passin pass:{{.CA_PASS}} \
          -CAcreateserial -out "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/{{.SERVICE}}.crt" \
          -sha256 \
          -extfile "{{.ROOT_DIR}}/services/{{.SERVICE}}/security/cert.conf" \
          -extensions v3_req

  gen-jwt-keys:
    desc: "Generate JWT RSA keys for SSO and copy public key to Billing"
    cmds:
      - mkdir -p "{{.ROOT_DIR}}/services/sso/security"
      - openssl genrsa -out "{{.ROOT_DIR}}/services/sso/security/private.pem" {{.JWT_BITS}}
      - openssl rsa -in "{{.ROOT_DIR}}/services/sso/security/private.pem" -pubout -out "{{.ROOT_DIR}}/services/sso/security/public.pem"
      - mkdir -p "{{.ROOT_DIR}}/services/billing/security"
      - cp "{{.ROOT_DIR}}/services/sso/security/public.pem" "{{.ROOT_DIR}}/services/billing/security/public.pem"
    generates:
      - "{{.ROOT_DIR}}/services/sso/security/private.pem"
      - "{{.ROOT_DIR}}/services/sso/security/public.pem"
      - "{{.ROOT_DIR}}/services/billing/security/public.pem"

  gen-postman:
    desc: "Generatepfx for postman"
    cmds:
      - openssl pkcs12 -export -out "{{.ROOT_DIR}}/security/postman.pfx" -inkey "{{.ROOT_DIR}}/services/client/security/client.key" -in "{{.ROOT_DIR}}/services/client/security/client.crt" -certfile "{{.ROOT_DIR}}/security/ca.crt" -password pass:{{.CA_PASS}}
  
  password-for-nginx:
    desc: "Copy password to file for nginx"
    cmds:
      - echo {{.CA_PASS}} > "{{.ROOT_DIR}}/security/passphrase.txt"

  all:
    desc: "Выполнить всю цепочку генерации сертификатов"
    cmds:
      - task: generate-ca
      - task: copy-ca-to-services
      - task: generate-service-certs
      - task: gen-jwt-keys
      - task: password-for-nginx

  check-certs:
    desc: "Check certificate details"
    cmds:
      - echo "\n=== transaction ==="
      - openssl x509 -in "{{.ROOT_DIR}}/services/transaction/security/transaction.crt" -noout -text | grep -E "Subject:|Issuer:|Not Before|Not After"
      - echo "\n=== sso ==="
      - openssl x509 -in "{{.ROOT_DIR}}/services/sso/security/sso.crt" -noout -text | grep -E "Subject:|Issuer:|Not Before|Not After"
      - echo "\n=== billing ==="
      - openssl x509 -in "{{.ROOT_DIR}}/services/billing/security/billing.crt" -noout -text | grep -E "Subject:|Issuer:|Not Before|Not After"
      - echo "\n=== client ==="
      - openssl x509 -in "{{.ROOT_DIR}}/services/client/security/client.crt" -noout -text | grep -E "Subject:|Issuer:|Not Before|Not After"